### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by andybak** [dlobser/Sugar#1]
Hi,

I started playing with particles and VR and it suddenly occurred to me to see if you'd posted the source for Cosmic Sugar. I'm assuming this is it!

There's no licence file so I'm not sure whether it's OK to nab any ideas or bits of code from this.

My thing is here: https://andybak.itch.io/xparticles-vr

It's heavily based on an existing project and I've only spent a couple of hours on it so far - but I'll push it to Github with an MIT licence to match the project I pilfered most of the code from. 

It would be fab if you added a similar licence to this repo. Then I could encourage other people to start mix and matching from both code bases.

**Comment by dlobser** [comment]
Hey Andy - I'm pretty proud of the results of Cosmic Sugar - but not my code - it's kind of a mess, I'm sure the repo you started with is in much better shape.

**Comment by andybak** [comment]
Hi David, thanks for the response. It would still be useful to have a clear licence on your repos. Are you intending them to be open source? GPL or MIT?

I've been having a play with TREE and it looks really interesting. I'd like to know if it's worth me spending time figuring out how to use it.
